name: quantum-ml
channels:
  - nvidia/label/cuda-12.4.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - mpi4py>=3.1.4
  - openmpi>=5.0.3
  - cxx-compiler
  - numpy>=1.23.0,<1.25.0
  - scikit-learn=1.3.0
  - qiskit=0.43.0
  - pennylane=0.35.1
  - pytest=7.4.0
  - matplotlib=3.8.2
  - black=23.0.0
  - isort=5.12.0
  - pip:
    - cudaq 